version: '3.8'
services:
  hamiweb:
    image: razava/hamiweb:latest
    restart: always
    ports:
      - "127.0.0.1:6770:6679"
    networks:
      - oyoon-api_default

networks:
  oyoon-api_default:
    external: true