import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Provider from "../utils/ReactQuery/Provider";
import { Toaster as SonnerToaster } from "@/components/ui/sonner";
import ProgressBarProviders from "@/components/PrograssBar";
import { EnvScript, PublicEnvScript } from "next-runtime-env";

export const metadata: Metadata = {
  title: "حامی",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <PublicEnvScript />
      </head>
      <body className="font-[yekan] bg-white">
        <Provider>
          <ProgressBarProviders>{children}</ProgressBarProviders>
          <Toaster />
          <SonnerToaster richColors />
        </Provider>
      </body>
    </html>
  );
}
