name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*.*.*" # اجرای workflow برای تگ‌های نسخه
  workflow_dispatch: # امکان اجرای دستی workflow

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            razava/hamiweb # نام مخزن در Docker Hub
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }} # نام کاربری Docker Hub از Secrets
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }} # رمز عبور یا Token از Secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: "./Dockerfile" # مسیر فایل Dockerfile (در صورت تغییر به مسیر موردنظر بروزرسانی کنید)
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
